# Site settings
title: Endurance And The Pursuit Of Happiness
header-img: img/home-bg.png
email: jciringione@gmail.com
copyright_name: jbok4
description: > # this means to ignore newlines until "baseurl:"
  Stories from a Coding Education, by Jaclyn Ciringione
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: jbok4
github_username:  jbok4
learn_profile: jbok4
email_username: jciringione@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
